project/models.py
from sqlalchemy.ext.hybrid import hybrid_method

from project.ext import db


class Recipe(db.Model):
    __tablename__ = "recipes"
    id = db.Column(db.Integer, primary_key=True)
    recipe_title = db.Column(db.String, nullable=False)
    recipe_description = db.Column(db.String, nullable=False)

    def __init__(self, title, description):
        self.recipe_title = title
        self.recipe_description = description

    def __repr__(self):
        return '<title {}'.format(self.name)


class User(db.Model):

    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    email = db.Column(db.String, unique=True, nullable=False)
    password_plaintext = db.Column(db.String, nullable=False)  # TEMPORARY - TO BE DELETED IN FAVOR OF HASHED PASSWORD
    authenticated = db.Column(db.Boolean, default=False)

    def __init__(self, email, password_plaintext):
        self.email = email
        self.password_plaintext = password_plaintext
        self.authenticated = False

    @hybrid_method
    def is_correct_password(self, plaintext_password):
        return self.password_plaintext == plaintext_password

    @property
    def is_authenticated(self):
        # Return True if user authenticated
        return self.authenticated

    @property
    def is_active(self):
        # always true, as all user are active
        return True

    @property
    def is_anonymous(self):
        # always false as all user aren't supported
        return False

    def get_id(self):
        """Return the email address to satisfy Flask-Login's requirements."""
        """Requires use of Python 3"""
        return str(self.id)

    def __repr__(self):
        return '<User {0}>'.format(self.name)

project/recipes/forms.py
from flask_wtf import Form
from wtforms import StringField
from wtforms.validators import DataRequired


class AddRecipeForm(Form):
    recipe_title = StringField('Recipe Title', validators=[DataRequired()])
    recipe_description = StringField('Recipe Description', validators=[DataRequired()])

project/__init__.py
from flask import Flask

from .ext import login_manager, db

app = Flask(__name__, instance_relative_config=True)
app.config.from_object('project.config.Baseconfig')

from project.models import User


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter(User.id == int(user_id)).first()


from project.users.views import users_blueprint
from project.recipes.views import recipes_blueprint

app.register_blueprint(users_blueprint)
app.register_blueprint(recipes_blueprint)

project/recipes/views.py
from flask import render_template, Blueprint, request, redirect, url_for, flash

from project.ext import db
from project.models import Recipe
from project.recipes.forms import AddRecipeForm

recipes_blueprint = Blueprint('recipes', __name__, template_folder='templates')


@recipes_blueprint.route('/')
def index():
    all_recipe = Recipe.query.all()
    return render_template('recipes.html', recipes=all_recipe)


@recipes_blueprint.route('/add', methods=['GET', 'POST'])
def add_recipe():
    form = AddRecipeForm(request.form)
    if request.method == 'POST':
        if form.validate():
            new_recipe = Recipe(form.recipe_title.data, form.recipe_description.data)
            flash('New recipe, {}, added!'.format(new_recipe.recipe_title), 'success')
            db.session.add(new_recipe)
            db.session.commit()
            return redirect(url_for('recipes.index'))
        else:
            flash('ERROR! Recipe was not added.', 'error')
    return render_template('add_recipe.html', form=form)

project/users/views.py
from sqlite3 import IntegrityError

from flask import render_template, Blueprint, request, flash, redirect, url_for
from flask_login import logout_user, login_required
from sqlalchemy.sql.functions import current_user

from project.ext import db
from flask_login import login_user
from project.models import User
from project.users.form import RegisterForm, LoginForm

users_blueprint = Blueprint('users', __name__)
# login_required =


# @users_blueprint.route('/login')
# def login():
#     return render_template('login.html')


@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST':
        if form.validate():
            try:
                new_user = User(form.email.data, form.password.data)
                new_user.authenticated = True
                db.session.add(new_user)
                db.session.commit()
                flash('Thanks for registering!', 'success')
                return redirect(url_for('recipes.index'))
            except IntegrityError:
                db.session.rollback()
                flash('ERROR! Email ({}) already exists.'.format(form.email.data), 'error')
                return render_template('register.html', form=form)
    return render_template('register.html', form=form)


@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)

    if request.method == 'POST':
        if form.validate():
            user = User.query.filter_by(email=form.email.data).first()
            if user is not None and user.is_correct_password(form.password.data):
                user.authenticated = True
                db.session.add(user)
                db.session.commit()
                login_user(user)
                # flash('Thanks for logging in, {}'.format(current_user))
                return redirect(url_for('recipes.index'))
            else:
                flash('ERROR! Incorrect login credentials.', 'error')
                return render_template('login.html', form=form)
    return render_template('login.html', form=form)


@users_blueprint.route('/logout')
@login_required
def logout():
    user = current_user
    user.authenticated = False
    # db.session.add(user)
    db.session.commit()
    logout_user()
    flash('Goodbye', 'info')
    return redirect(url_for('users.login'))

project/templates/_form_macros.html
{% macro render_field(field) %}
 
<dt>{{ field.label }}:
 
<dd>{{ field(**kwargs)|safe }}
{% if field.errors %}
<span class="error">
{% for error in field.errors %}
{{ error }}
{% endfor %}
</span>
{% endif %}
</dd>
 
{% endmacro %}

project/templates/add_recipe.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}
 
<div class="add-recipe">
<div class="page-header">
<h2>Add a New Recipe</h2>
</div>
 
<form action="{{ url_for('recipes.add_recipe') }}" method="post">
{{ form.csrf_token }}

<dl>
{{ render_field(form.recipe_title, placeholder="Enter Recipe Title") }}
{{ render_field(form.recipe_description, placeholder="Enter Recipe Description") }}
</dl>

<button class="btn btn-sm btn-success" type="submit">Add Recipe</button>
</form>

</div>
 
{% endblock %}

project/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="Kennedy Family Recipe App">
<meta name="author" content="Patrick Kennedy">
<title>Kennedy Family Recipe App</title>
<!-- styles -->
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>

<body>
<!-- flash messages -->
{% for error_message in get_flashed_messages(category_filter=["error"]) %}

<div class="alert alert-danger alert-dismissible">{{ error_message }}</div>

{% endfor %}

{% for success_message in get_flashed_messages(category_filter=["success"]) %}

<div class="alert alert-success alert-dismissible">{{ success_message }}</div>

{% endfor %}

{% for info_message in get_flashed_messages(category_filter=["info"]) %}

<div class="alert alert-info alert-dismissible">{{ info_message }}</div>

{% endfor %}

<!-- Static navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
<div class="container">

<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#recipes-navbar-collapse-1" aria-expanded="false">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="{{ url_for('recipes.index') }}">Kennedy Family Recipes</a>
</div>

<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="recipes-navbar-collapse-1">
<ul class="nav navbar-nav">
<li><a href="#">Breakfast Recipes</a></li>
<li><a href="#">Lunch Recipes</a></li>
<li><a href="#">Dinner Recipes</a></li>
<li><a href="#">Dessert Recipes</a></li>
    <li><a href="{{ url_for('recipes.add_recipe') }}">Add Recipe</a></li>
    <li><a href="{{ url_for('users.register') }}">Register</a></li>
    <li><a href="{{ url_for('users.login') }}">Log In</a></li>
    <li><a href="{{ url_for('users.logout') }}">Log Out</a></li>
</ul>
<ul class="nav navbar-nav navbar-right">
<li><a href="#">Welcome!</a></li>
</ul>
</div><!--/.nav-collapse -->
</div><!-- /.container -->
</nav>

<div class="container">
<div class="content">

<!-- child template -->
{% block content %}
{% endblock %}

</div>
<div class="footer">
<hr>
<p>by Dzikri Kovalesky - 2022</p>
</div>
</div><!-- /.container -->

<!-- scripts -->
<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</body>
</html>

project/templates/login.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}
 
{% block content %}
 
<div class="user-registration">
<div class="page-header">
<h2>Log In</h2>
</div>
<form action="{{ url_for('users.login') }}" method="post">
{{ form.csrf_token }}
<dl>
{{ render_field(form.email, placeholder="Email address") }}
{{ render_field(form.password, placeholder="Password") }}
</dl>
<button class="btn btn-sm btn-success" type="submit">Log In</button>
</form>
<em>Need an account? </em><a href="/register">Signup!!</a>
</div>
 
{% endblock %}

project/templates/recipes.html
{% extends "layout.html" %}
{% block content %}
 
<div class="page-header">
<h2>Recipes</h2>
</div>
<div class="row">
<div class="col-md-4">
<table class="table table-striped" id="owned_stock_table">
<thead>
<tr>
<th>Title</th>
<th>Description</th>
</tr>
</thead>
<tbody>
{% for recipe in recipes %}
<tr>
<td>{{ recipe.recipe_title }}</td>
<td>{{ recipe.recipe_description }}</td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>
 
{% endblock %}

project/templates/register.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}
 
{% block content %}
<div class="user-registration">
<div class="page-header">
<h2>Please Register Your New Account</h2>
</div>
<form action="{{ url_for('users.register') }}" method="post">
{{ form.csrf_token }}
<dl>
{{ render_field(form.email, placeholder="Email address") }}
{{ render_field(form.password, placeholder="Password") }}
{{ render_field(form.confirm, placeholder="Confirm password") }}
</dl>
<button class="btn btn-sm btn-success" type="submit">Create New Account</button>
</form>
</div>
 
{% endblock %}